name: buildflow_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter

   
  get: ^4.6.6
  http: ^0.13.6

  flutter_secure_storage: ^5.0.2 
  logger: ^2.0.2  
  image_picker: ^1.0.7





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  get: ^4.7.2
=======
  file_picker: ^5.0.1 # or the latest version
  webview_flutter: ^4.2.1 # Add this line for WebView support
  flutter_secure_storage: ^5.0.2 
  logger: ^2.0.2  
  image_picker: ^1.0.7

>>>>>>> 3c6d5fa5d111c9154620ac85d42783745a2e15a4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
    
  assets:
      - assets/office.png
      - assets/user.png  #   - images/a_dot_ham.jpeg
      - assets/company.png
      - assets/logo.png
      - assets/logo.jpg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package